#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import win32gui, win32con
import threading
import subprocess
import requests
import time

from Cheese.cheese import CheeseBurger
from Cheese.appSettings import Settings
from Cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if ("-nocons" in sys.argv):
    prog = win32gui.GetForegroundWindow()
    win32gui.ShowWindow(prog, win32con.SW_HIDE)

def runFileServer():
    subprocess.call(ResMan.joinPath(ResMan.resources(), "fileServer.bat"))

if __name__ == "__main__":
    CheeseBurger.init()

    i = 0
    while i < 10:
        try:
            req = {
                "name": Settings.name,
                "port": Settings.port,
                "icon": "/images/folder.png",
                "color": "FF0000"
            }
            requests.post(f"http://localhost/services/doYouKnowMe", json=req)
            break
        except:
            i += 1
            time.sleep(1)

    x = threading.Thread(target=runFileServer)
    x.start()

    CheeseBurger.serveForever()