#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import time
import threading
import os

from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer

from Cheese.cheese import CheeseBurger
from Cheese.appSettings import Settings
from Cheese.resourceManager import ResMan
from Cheese.Logger import Logger

"""
File generated by Cheese Framework

main file of Cheese Application
"""

def runFileServer():
    authorizer = DummyAuthorizer()

    authorizer.add_user('user', '12345', '.', perm='elradfmwMT')
    authorizer.add_anonymous(os.getcwd())

    handler = FTPHandler
    handler.authorizer = authorizer

    handler.banner = "pyftpdlib based ftpd ready."

    address = ('0.0.0.0', 21)
    server = FTPServer(address, handler)

    server.max_cons = 256
    server.max_cons_per_ip = 5

    Logger.info("FTP SERVER IS RUNNING")
    server.serve_forever()


if __name__ == "__main__":
    CheeseBurger.init()

    i = 0
    while i < 1:
        try:
            req = {
                "name": Settings.name,
                "port": Settings.port,
                "icon": "/images/gridIcons/frogieCloud.png",
                "color": "FF0000"
            }
            requests.post(f"http://localhost/services/doYouKnowMe", json=req)
            break
        except:
            i += 1
            time.sleep(1)

    x = threading.Thread(target=runFileServer)
    x.start()

    CheeseBurger.serveForever()