#!/usr/bin/env python
# -*- coding: utf-8 -*-

from http.server import BaseHTTPRequestHandler

from cheese.modules.cheeseController import CheeseController
from python.authorization import Authorization

#REST CONTROLLERS


"""
File generated by Cheese Framework

server handler of Cheese Application
"""

class CheeseServer(BaseHTTPRequestHandler):
    def do_GET(self):
        path = CheeseController.getPath(self.path)
        auth = None

        if (path == "/"):
            CheeseController.serveFile(self, "index.html")
        else:
            CheeseController.serveFile(self, self.path)

        pass

    def do_POST(self):
        auth = None


        pass