#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from cheese.cheese import Cheese
from cheese.resourceManager import ResMan

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if __name__ == "__main__":
    Cheese.init()

    filesPath = os.path.join(ResMan.web(), "files")
    if (not os.path.exists(filesPath)):
        os.mkdir(filesPath)

    Cheese.serveForever()