#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import time

from cheese.cheese import Cheese
from cheese.appSettings import Settings

"""
File generated by Cheese Framework

main file of Cheese Application
"""

if __name__ == "__main__":
    Cheese.init()

    time.sleep(1)
    requests.get(f"http://localhost:80/services/doYouKnowMe?name=Frogie_Cloudos&port={Settings.port}&icon=frogieCloud.png")

    Cheese.serveForever()